### ISSUE TITLE
[QUESTION]: SENDRQ, GETRQ, GETST codes. 

### ISSUE THREAD

**Issue by Demellion** [TheMysteriousVincent/ArmA3URLFetch#30]
In a return codes page it was stated that those commands handle HTTP codes (>100). But I seem to be recieving only 0 and 1, which is done and pending custom codes from extension. How to handle something like 200, 404 or 502 for example? 
Thanks.

EDIT: Also all of those commands support HTTP codes >100?

**Comment by pixlcrashr** [comment]
Hey there!
Thanks for your question. For example, take a look at the `fn_request.sqf` source file:
https://github.com/playnet-public/ArmA3URLFetch/blob/master/addons/common/functions/fn_request.sqf

The HTTP status code is returned after the text buffer of the result is cleared. This means, you have to get all contents with `GETRQ`.
The last call of `GETRQ` will return the HTTP status code as the `callExtension` return code of the "Alternative Syntax" (https://community.bistudio.com/wiki/callExtension).

I have also updated the return code list, because HTTP status codes are only returned by the final call of `GETRQ`.
